/**
 * Games page catalogue.
 *
 * Three sources, all legitimate:
 *  - `archiveCollections`: thousands of classic titles legally hosted and
 *    made playable in-browser by the Internet Archive (emulated with EM-DOSBox).
 *  - `openSourceGames`: freely licensed / open-source HTML5 games that allow
 *    embedding, playable directly in a frame.
 *  - `portals`: legit free-to-play destinations, opened in the proxy browser.
 */

export const gamesConfig = {
  heading: "Quantum Games",
  subheading:
    "Thousands of playable classics from the Internet Archive, a shelf of open-source web games, and the best free game portals.",
  archiveCollections: [
    { id: "softwarelibrary_msdos_games", label: "MS-DOS classics" },
    { id: "softwarelibrary_win3_games", label: "Windows 3.x" },
    { id: "softwarelibrary_apple", label: "Apple II" },
    { id: "softwarelibrary_c64_games", label: "Commodore 64" },
    { id: "softwarelibrary_zx_spectrum", label: "ZX Spectrum" },
    { id: "handheldhistory", label: "Handheld LCD" },
    { id: "internetarcade", label: "Internet Arcade" },
    { id: "softwarelibrary_msdos_shareware", label: "DOS shareware" },
    { id: "softwarelibrary_amiga", label: "Amiga" },
    { id: "softwarelibrary_atari_800", label: "Atari 800" },
    { id: "atari_2600_library", label: "Atari 2600" },
    { id: "softwarelibrary_msx", label: "MSX" },
    { id: "softwarelibrary_bbcmicro", label: "BBC Micro" },
    { id: "softwarelibrary_zxspectrum_games", label: "Spectrum games" },
    { id: "vintagesoftware", label: "Vintage software" },
    { id: "classicpcgames", label: "Classic PC games" },
    { id: "open_source_software", label: "Open source" },
  ],
  openSourceGames: [
    { label: "2048", url: "https://play2048.co", tag: "Puzzle" },
    { label: "Hextris", url: "https://hextris.io", tag: "Puzzle" },
    { label: "Astray", url: "https://wwwtyro.github.io/Astray/", tag: "Maze" },
    { label: "HexGL", url: "https://hexgl.bkcore.com/play/", tag: "Racing" },
    { label: "Kiwi Clicker", url: "https://gd.games", tag: "Casual" },
    { label: "Sudoku", url: "https://sudoku.com", tag: "Puzzle" },
    { label: "Minesweeper", url: "https://minesweeper.online", tag: "Puzzle" },
    { label: "Tetris (Open)", url: "https://tetris.com/play-tetris", tag: "Arcade" },
    { label: "Freeciv Web", url: "https://play.freeciv.org", tag: "Strategy" },
    { label: "Xterm Chess (Lichess)", url: "https://lichess.org", tag: "Board" },
    { label: "OpenArena Ports", url: "https://openarena.ws", tag: "Shooter" },
    { label: "The Powder Toy", url: "https://powdertoy.co.uk", tag: "Sandbox" },
    { label: "Bloxorz", url: "https://www.coolmathgames.com/0-bloxorz", tag: "Puzzle" },
    { label: "Slither.io", url: "https://slither.io", tag: ".io" },
    { label: "Agar.io", url: "https://agar.io", tag: ".io" },
    { label: "Diep.io", url: "https://diep.io", tag: ".io" },
    { label: "Paper.io", url: "https://paper-io.com", tag: ".io" },
    { label: "Wordle (NYT)", url: "https://www.nytimes.com/games/wordle", tag: "Word" },
    { label: "Krunker", url: "https://krunker.io", tag: "Shooter" },
    { label: "Shell Shockers", url: "https://shellshock.io", tag: "Shooter" },
    { label: "Skribbl", url: "https://skribbl.io", tag: "Party" },
    { label: "Gartic Phone", url: "https://garticphone.com", tag: "Party" },
    { label: "Territorial.io", url: "https://territorial.io", tag: "Strategy" },
    { label: "Little Alchemy 2", url: "https://littlealchemy2.com", tag: "Puzzle" },
    { label: "GeoGuessr-like: Globle", url: "https://globle-game.com", tag: "Geo" },
    { label: "Chess vs Stockfish", url: "https://lichess.org/practice", tag: "Board" },
    { label: "OpenTyrian", url: "https://lostdecadegames.github.io/opentyrian/", tag: "Shooter" },
    { label: "BrowserQuest", url: "https://browserquest.herokuapp.com", tag: "MMO" },
    { label: "Space Company", url: "https://sparticle999.github.io/SpaceCompany/", tag: "Idle" },
    { label: "Cookie Clicker", url: "https://orteil.dashnet.org/cookieclicker/", tag: "Idle" },
    { label: "A Dark Room", url: "https://adarkroom.doublespeakgames.com", tag: "Text" },
    { label: "Candy Box 2", url: "https://candybox2.github.io", tag: "Idle" },
    { label: "Doom (Archive)", url: "https://archive.org/details/DoomsharewareEpisode", tag: "Retro" },
    { label: "Quake JS", url: "https://www.quakejs.com", tag: "Shooter" },
    { label: "Screeps Arena demo", url: "https://screeps.com", tag: "Coding" },
    { label: "Vampire Survivors (web)", url: "https://poncle.itch.io/vampire-survivors", tag: "Action" },
    { label: "Slope", url: "https://slopegame.online", tag: "Arcade" },
  ],
  portals: [
    { label: "itch.io free web games", url: "https://itch.io/games/free/platform-web" },
    { label: "Poki", url: "https://poki.com" },
    { label: "CrazyGames", url: "https://www.crazygames.com" },
    { label: "Newgrounds", url: "https://www.newgrounds.com/games" },
    { label: "Kongregate", url: "https://www.kongregate.com" },
    { label: "Lichess", url: "https://lichess.org" },
    { label: "Chess.com", url: "https://www.chess.com/play" },
    { label: "Skribbl.io", url: "https://skribbl.io" },
    { label: "Jackbox (browser)", url: "https://jackbox.tv" },
    { label: "GDevelop games", url: "https://gd.games" },
    { label: "Armor Games", url: "https://armorgames.com" },
    { label: "Miniclip", url: "https://www.miniclip.com" },
    { label: "Y8", url: "https://www.y8.com" },
    { label: "Addicting Games", url: "https://www.addictinggames.com" },
    { label: "Coolmath Games", url: "https://www.coolmathgames.com" },
    { label: "Internet Arcade", url: "https://archive.org/details/internetarcade" },
    { label: "Flashpoint Web", url: "https://flashpointarchive.org" },
    { label: "Game Jolt", url: "https://gamejolt.com/games" },
  ],
};
